app:
  domainUrl: http://localhost:8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
#    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    h2:
#      console:
#        enabled: true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo
    username: root
    password: 7845120qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - profile
              - email
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secretKey: SeCrEtKeY4HaShInG
  access:
    expiration: 3600000
  refresh:
    expiration: 1209600000

azure:
  ocr:
    endpoint: ${AZURE_OCR_ENDPOINT:azure_ocr_endpoint}
    key: ${AZURE_OCR_KEY:azure_ocr_key}